### Регистрация
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "email": "sem4ezz+3@gmail.com",
  "password": "Password123!"
}

### Подтверждение кода
POST http://localhost:5001/api/auth/verify-code
Content-Type: application/json

{
  "email": "sem4ezz+3@gmail.com",
  "code": "301138"
}

### Вход
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "leninnnnz@gmail.com",
  "password": "Password123!"
}